### ISSUE TITLE
Bring Images offline ( Difficulty - Easy)

### ISSUE THREAD

**Issue by EmberCS15** [NJACKWinterOfCode/Wizzy-Downloader#1]
Currently, the images used on the home page are not stored in the images folder( location - /downloader/static/downloader/images/) but are referenced directly from the internet using their respective links. If the internet connection is slow it results in a lot of latency.
1. Download the images and make required changes to the following files so that the code works as before but with the downloaded images.
Files to be changed - index.html
Tag - JavaScript,Django Tags(Read up on the static tag in Django)
2. The image for the link to youtube from the home page seems to be corrupted which results in the image not being displayed . Find a new image to replace it.
Files to be changed - index.html
Difficulty - Easy

**Comment by vanshsoni** [comment]
Hey I have done this can I make PR for this 
added the new image for youtube icon
images are offline now

**Comment by EmberCS15** [comment]
Hey Vansh,
You can surely make the PR. Keep Up the good work and try your hand on the
other issues.
Cheers
Abhijit Roy
Mentor

(P.S - You can reach out to me personally over WhatsApp(7258062484)).

**Comment by EmberCS15** [comment]
This issue has been solved by @vanshsoni .
